"""Edit table columns

Revision ID: c6a99eaf2697
Revises: 
Create Date: 2023-12-24 12:39:53.436639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6a99eaf2697'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_mono', sa.String(), nullable=True),
    sa.Column('title_known', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_mono', sa.String(), nullable=True),
    sa.Column('commentator', sa.String(), nullable=True),
    sa.Column('commentator_mono', sa.String(), nullable=True),
    sa.Column('translator', sa.String(), nullable=True),
    sa.Column('translator_mono', sa.String(), nullable=True),
    sa.Column('compiler', sa.String(), nullable=True),
    sa.Column('compiler_mono', sa.String(), nullable=True),
    sa.Column('date_written', sa.Date(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subjects', sa.String(), nullable=True),
    sa.Column('quantity_sheet', sa.VARCHAR(length=150), nullable=True),
    sa.Column('quantity_ill', sa.VARCHAR(length=150), nullable=True),
    sa.Column('lines', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('size', sa.VARCHAR(length=100), nullable=True),
    sa.Column('paper', sa.VARCHAR(length=100), nullable=True),
    sa.Column('copyist', sa.VARCHAR(length=255), nullable=True),
    sa.Column('copy_date', sa.Date(), nullable=True),
    sa.Column('copy_place', sa.String(), nullable=True),
    sa.Column('type_handwriting', sa.VARCHAR(length=200), nullable=True),
    sa.Column('cover', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cover_color', sa.VARCHAR(length=200), nullable=True),
    sa.Column('stamp', sa.VARCHAR(length=255), nullable=True),
    sa.Column('text_begin', sa.String(), nullable=True),
    sa.Column('text_exbegin', sa.String(), nullable=True),
    sa.Column('text_ammabegin', sa.String(), nullable=True),
    sa.Column('text_end', sa.String(), nullable=True),
    sa.Column('text_exend', sa.String(), nullable=True),
    sa.Column('colophon', sa.String(), nullable=True),
    sa.Column('defects', sa.String(), nullable=True),
    sa.Column('fixation', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('descript_auth', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
